#ifndef POKEMON_GEN1_LINK_PROTOCOL_H
#define POKEMON_GEN1_LINK_PROTOCOL_H

typedef enum
{
	UNKNOWN,
	NOT_CONNECTED,
	CONNECTED,
	TRADE_CENTRE,
	COLOSSEUM
} connection_state_t;

typedef enum
{
	INIT,
	SEND_RAND0,
	SEND_RAND1,
	SEND_RAND2,
	SEND_RAND3,
	SEND_RAND4,
	SEND_RAND5,
	SEND_RAND6,
	SEND_RAND7,
	SEND_RAND8,
	SEND_RAND9,
	WAIT,
	SEND_DATA,
	SEND_PATCH
} trade_centre_state_t;

typedef unsigned char byte;

#define PKMN_BLANK 0x00

#define ITEM_1_HIGHLIGHTED 0xD0
#define ITEM_2_HIGHLIGHTED 0xD1
#define ITEM_3_HIGHLIGHTED 0xD2
#define ITEM_1_SELECTED 0xD4
#define ITEM_2_SELECTED 0xD5
#define ITEM_3_SELECTED 0xD6

#define PKMN_MASTER 0x01
#define PKMN_SLAVE 0x02
#define PKMN_CONNECTED 0x60
#define PKMN_WAIT 0x7F
#define PKMN_NO_DATA 0xFE

#define PKMN_ACTION 0x60

#define PKMN_TRADE_CENTRE ITEM_1_SELECTED
#define PKMN_COLOSSEUM ITEM_2_SELECTED
#define PKMN_BREAK_LINK ITEM_3_SELECTED

#define TRADE_CENTRE_WAIT 0xFD

#endif /* POKEMON_GEN1_LINK_PROTOCOL_H */
